### PR TITLE
Add skeleton command test case

### PR DESCRIPTION
**Pull request by nafiesl**
This package is a nice starting point for create a laravel package, thanks for creating this.

I have read a reference from this [symfony console documentation](https://symfony.com/doc/current/console.html#testing-commands) to make a console command test. I create a test case for this package. This PR contains a test case for the `skeleton` command. Could you please review this PR and merge to master branch?

Thank you.

### CODE REVIEW

**Comment by nasrulhazim** [comment]
@nafiesl , how to make request from Travis, to check this PR?

**Comment by nasrulhazim** [comment]
@nafiesl , can you update your codes - I've added `.travis.yaml` and update `README.md` - and make a new PR, just to ensure the travis ci is running.

**Comment by nafiesl** [comment]
Sure, i will push new commit to this PR.

**Comment by nasrulhazim** [comment]
thank you @nafiesl !

**Pull request merged**
