### PR TITLE
Add environment check to prevent "composer install" execution on testing

### PR DESCRIPTION
**Pull request by nafiesl**

### CODE REVIEW

**Comment by nasrulhazim** [comment]
@nafiesl , do we need `phpdotenv` package as dependency?

**Comment by nafiesl** [comment]
Ah, I haven't try this package for production (generating new package). I will try this patch on on my local dev. I will update the PR if i got problem with the `env()` function. Thanks.

**Comment by nafiesl** [comment]
I already check that we don't need additional `phpdotenv` as dependency.
I try to use `dd(env('APP_ENV'));` on `ComposerTrait@composerInstall` and it returns `null`.
`null != 'testing'` means we have no problem on production. :+1: 

shutter_20180114-003

shutter_20180114-004

Then Insyaallah this PR is safe to be merged. :grin:

**Comment by nasrulhazim** [comment]
alright, good work @nafiesl !

**Pull request merged**
